# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci"];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.resumeDevice = config.fileSystems."/".device;
  boot.kernelParams = [ "resume_offset=64292864" ]; # location of swap in its partition
  boot.kernel.sysctl = { "vm.swappiness" = 1; };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a857356c-5021-476a-8394-6fc4ee0763cb";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/00D8-FE33";
      fsType = "vfat";
    };

  swapDevices = [
    {
      #label = "swapfile";
      device = "/swapfile";
      size = 8 * 1024; # 8 GiB expressed in MiB
    }
  ];

  nix.maxJobs = lib.mkDefault 4;
}
