# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, nixpkgs, ... }:

{
  imports =
    [ (nixpkgs + "/nixos/modules/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d053db35-a248-4faf-bc7d-06c7865d882f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptrot".device = "/dev/disk/by-uuid/6514eb1d-dbb4-4273-8ad3-962a05b12c61";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/cdf27ccf-6145-4a18-82e5-636a6d300521";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
  #powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
