# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "aesni_intel" "cryptd" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.resumeDevice = config.fileSystems."/".device;
  boot.kernelParams = [ "resume_offset=17993728" ]; # location of swap in its partition

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a0f47bce-6649-4076-9e63-aa6cea63be28";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/f57d541c-9060-42f9-ae64-53e26d8abcb9";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0F8A-0D1E";
    fsType = "vfat";
  };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.video.hidpi.enable = lib.mkDefault true;
}
